# Generated by Django 5.2.8 on 2025-11-20 05:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees (0-360)', max_digits=5, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Location accuracy in meters', max_digits=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, help_text='Zone radius in kilometers', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Operating hours by day of week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=False)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('cancelled_deliveries', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('scooter', 'Scooter')], default='bike', max_length=50)),
                ('vehicle_plate', models.CharField(blank=True, max_length=20)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Driver Availabilities',
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='estimated_arrival',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='picked_up_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='actual_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_photo',
            field=models.ImageField(blank=True, help_text='Proof of delivery photo', null=True, upload_to='deliveries/proof/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated delivery time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer rating (1-5)', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='signature',
            field=models.TextField(blank=True, help_text='Customer signature (base64)'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Driver current latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Driver current longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned to Driver'), ('accepted', 'Accepted by Driver'), ('picked_up', 'Picked Up'), ('en_route', 'En Route to Customer'), ('arrived', 'Arrived at Location'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed Delivery')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['driver', 'status'], name='delivery_de_driver__70c776_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['status', 'created_at'], name='delivery_de_status_317f2f_idx'),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='driveravailability',
            name='driver',
            field=models.OneToOneField(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deliverylocation',
            index=models.Index(fields=['delivery', '-timestamp'], name='delivery_de_deliver_e3cd16_idx'),
        ),
    ]
