# Generated by Django 5.2.8 on 2025-11-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_review_unique_together_review_order_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_restaurants',
            field=models.ManyToManyField(blank=True, help_text="User's favorite restaurants", related_name='favorited_by', to='restaurants.restaurant'),
        ),
    ]
