# Generated by Django 5.2.6 on 2025-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_restaurants'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_documents_uploaded',
            field=models.BooleanField(default=False, help_text='Whether driver has uploaded required documents'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_expiry',
            field=models.DateField(blank=True, help_text='Driver license expiration date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_number',
            field=models.CharField(blank=True, help_text='Driver license number', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_driver',
            field=models.BooleanField(default=False, help_text='Whether driver has been verified and approved'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_insurance_expiry',
            field=models.DateField(blank=True, help_text='Vehicle insurance expiration date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_plate',
            field=models.CharField(blank=True, help_text='Vehicle license plate number', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('bike', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('scooter', 'Scooter')], help_text='Type of vehicle for deliveries', max_length=20),
        ),
    ]
