# Generated by Django 5.2.6 on 2026-01-22 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('order_ready', 'Order Ready'), ('order_delivered', 'Order Delivered'), ('driver_assigned', 'Driver Assigned'), ('delivery_status', 'Delivery Status Update')], max_length=50)),
                ('backend', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('recipient', models.CharField(help_text='Email address, phone number, or user ID', max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message_data', models.JSONField(default=dict, help_text='Message content and template data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now, help_text='When to send this notification')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=5, help_text='Lower number = higher priority (1-10)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (order_id, user_id, etc.)')),
            ],
            options={
                'verbose_name': 'Notification Queue',
                'verbose_name_plural': 'Notification Queue',
                'ordering': ['priority', 'scheduled_for', 'created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='core_notifi_status_ee21ce_idx'), models.Index(fields=['notification_type', 'status'], name='core_notifi_notific_3e5cf0_idx'), models.Index(fields=['backend', 'status'], name='core_notifi_backend_a54fcd_idx'), models.Index(fields=['created_at'], name='core_notifi_created_246417_idx')],
            },
        ),
    ]
