# Generated by Django 5.2.8 on 2025-11-23 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('fast_food', 'Fast Food'), ('bakery', 'Bakery'), ('food_truck', 'Food Truck'), ('catering', 'Catering Service')], default='restaurant', max_length=50)),
                ('business_registration_number', models.CharField(blank=True, help_text='Business registration or tax ID', max_length=100)),
                ('bank_account_name', models.CharField(max_length=200)),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('application_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Tell us about your business')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='vendor_documents/licenses/')),
                ('health_certificate', models.FileField(blank=True, null=True, upload_to='vendor_documents/certificates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
