# Generated by Django 5.2.8 on 2025-11-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for order cancellation'),
        ),
    ]
