# Generated by Django 5.2.6 on 2026-01-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Pay Now (Online)'), ('cod', 'Cash on Delivery')], default='online', help_text='Payment method chosen during checkout', max_length=20),
        ),
    ]
