# Generated by Django 5.2.6 on 2026-01-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
