# Generated by Django 5.2.6 on 2026-01-17 22:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_postal_code'),
        ('restaurants', '0003_review_helpful_count_review_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Actual discount amount applied', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_restaurants',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='times_used',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='first_order_only',
            field=models.BooleanField(default=False, help_text='Only valid for first-time orders'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap (for percentage discounts)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_total_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Total usage limit (leave blank for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Times each user can use this coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order amount required', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Leave blank for platform-wide coupons', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_coupons', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('platform', 'Platform-wide'), ('restaurant', 'Restaurant-specific')], default='platform', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, help_text='Coupon code (case-insensitive)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (0-100) or fixed amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code', 'is_active'], name='orders_coup_code_3a9c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['valid_from', 'valid_until'], name='orders_coup_valid_f_fc9455_idx'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='orders_coup_coupon__b8b4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['used_at'], name='orders_coup_used_at_95247d_idx'),
        ),
    ]
